# Generated by Django 3.2.13 on 2022-06-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='date1',
        ),
    ]
