# Generated by Django 3.2.13 on 2022-06-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_date_task_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date1',
        ),
    ]
