# Generated by Django 3.2.13 on 2022-06-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_task_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-02-03'),
            preserve_default=False,
        ),
    ]
